services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: contact-book-frontend
    networks:
      - contact-book-frontend
    ports:
      - "8001:8001"
networks:
  contact-book-frontend:
    driver: bridge