services:
  api:
    build: .
    container_name: contact-book-api
    networks:
      - contact-book-backend
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:IFk6/BIx0fK+IVL2PId1qk96zKorPhNRVaWzz5zXozs=
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    expose:
      - "9000"   # deixa o PHP-FPM acess√≠vel para o Nginx

  nginx:
    image: nginx:alpine
    container_name: contact-book-nginx
    networks:
      - contact-book-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  sqlite:
    image: nouchka/sqlite3
    container_name: contact-book-sqlite
    networks:
      - contact-book-backend
    volumes:
      - ./database/database.sqlite:/root/db.sqlite
    tty: true
networks:
  contact-book-backend:
    driver: bridge